"""agregar alerta_inyeccion a analisis

Revision ID: 0440f51a6145
Revises: a9fa3e68d6be
Create Date: 2026-06-11 20:09:25.783405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0440f51a6145'
down_revision: Union[str, None] = 'a9fa3e68d6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('alerta_inyeccion', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis', 'alerta_inyeccion')
    # ### end Alembic commands ###
