"""agregar puntaje_llm a analisis

Revision ID: a9fa3e68d6be
Revises: 6c4d923b3ae8
Create Date: 2026-06-11 17:46:06.599411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fa3e68d6be'
down_revision: Union[str, None] = '6c4d923b3ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analisis', sa.Column('puntaje_llm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analisis', 'puntaje_llm')
    # ### end Alembic commands ###
