"""crear tabla analisis

Revision ID: f1689f331973
Revises: f4719f18a3b6
Create Date: 2026-06-11 13:13:53.497195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1689f331973'
down_revision: Union[str, None] = 'f4719f18a3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_del_candidato', sa.String(), nullable=True),
    sa.Column('archivo', sa.String(), nullable=False),
    sa.Column('titulo_trabajo', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trabajo_id'], ['tipos_de_trabajo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_id'), 'analisis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analisis_id'), table_name='analisis')
    op.drop_table('analisis')
    # ### end Alembic commands ###
